### ISSUE TITLE
[All] PowerBI Pro

### ISSUE THREAD

**Issue by abuzatu** [banica/2023_Cassini_Hackathon#2]
Marian, please add Pro licence to the PowerBI main account. Here are screenshots that show it is a free licence.
<img width="1271" alt="Screenshot 2023-10-08 at 21 25 16" src="https://github.com/banica/2023_Cassini_Hackathon/assets/33008499/3800cee6-d8bf-4a3a-addc-f10de7a2dd5e">

<img width="322" alt="Screenshot 2023-10-08 at 21 25 24" src="https://github.com/banica/2023_Cassini_Hackathon/assets/33008499/d76e05ef-9b57-4625-8ae7-bae7a7c0c966">

How to reproduce it:
* 1) Go to [PowerBI website](https://app.powerbi.com/user/user-settings/general?experience=power-bi)
* 2) Click on your username account on top right

**Comment by abuzatu** [comment]
@banica Great, I renamed the issue to a more general name, to discuss here all software:  Ensure we have the proper software locally and in cloud.

We can inspire software also from this data engineering competition on 18 Oct in Lausanne https://argusa.my.canva.site/data-challenge-october2023

**Comment by abuzatu** [comment]
For presentations, I see more and more people use Canva: https://www.canva.com It is collaborative online, several working on the presentation at the same time. It has a free version as well.

**Comment by abuzatu** [comment]
For creating and presenting the diagrams of how some flow works, including the team structure, the data flow in our pipeline, we use at work, and many people also use, Miro. https://miro.com

**Comment by abuzatu** [comment]
For Project management tools, we now use JIRA from Atlassian, but when we were smaller we were using Notion, which is actually better to use and also has a free Tier. https://www.notion.so

I also use it personally to create pages, documentations, keep track of tasks.

**Comment by abuzatu** [comment]
For dashboards, I would like us to try Tableau. https://www.tableau.com
Many companies use it. And it has a big plus that it runs natively on MacOS M2 processors like mine as well. So I do not have to install Windows locally on a virtual machine. That way I can use all my other infrastructure on Mac, and be productive. It has also local version or cloud version. It is from Salesforce. Linux and Windows people can also use the same tool.

**Comment by abuzatu** [comment]
By the way, I have already installed a virtual machine, but given the M2 processor I have for the Mac, it was only a development version. I got that working. But then Windows I was not able to start, either 10 or 11. Here are some screen shots to prove. So I would highly recommend we make it work so I can work on a Mac or via docker from Linux. So going with Tableau for dashboards.

<img width="1111" alt="Screenshot 2023-10-09 at 10 14 35" src="https://github.com/banica/2023_Cassini_Hackathon/assets/33008499/c91c7b80-298f-42d7-998d-ff8a71f8ddf3">

<img width="1244" alt="Screenshot 2023-10-09 at 10 32 24" src="https://github.com/banica/2023_Cassini_Hackathon/assets/33008499/887b6698-129b-4dd2-b978-5a5755ba227b">
<img width="181" alt="Screenshot 2023-10-09 at 10 33 03" src="https://github.com/banica/2023_Cassini_Hackathon/assets/33008499/d76ed938-8413-4825-96e2-18383b214180">
<img width="510" alt="Screenshot 2023-10-09 at 10 33 43" src="https://github.com/banica/2023_Cassini_Hackathon/assets/33008499/c5726a68-74ab-4e88-a85c-19af72bfc9ae">

**Comment by banica** [comment]
@abuzatu as far as i know Apple laptops are the only ones that are able to run easily Windows, Linux and Mac in the same time. 
I am highly recommend you to start using Linux, it is really next step forward in your dev career.

I will not help you to install Windows in a virtual machine, but i can tell you that license is a full license that you can use also for Windows Operating System.

So you have everything. Please try to check your hardware, i will not check it for you.

Regards,

**Comment by abuzatu** [comment]
@banica As I showed above, VirtualBox not support the new Arm processors only in a development version, which they no longer support. I did install it, and with it I did try to install Windows 10 and 11 and it did not work. Sure, maybe more effort can be put into this, but I do not convinced there is a solution. 

MacOS is a smart enough system to do everything inside. It is Unix-based, similar to Linux. So one can code internally as if in Linux. But I go to the next step. In my coding I use Docker with Linux, so that what works locally for me can be deployed automatically on a Linux server, as I did for the demos at the recent hackaton.

So overall, my ecosystem works fine. We just need to use solutions in the cloud for PowerBI. So if you can come back to your task of making this licence Pro, please :)

**Comment by banica** [comment]
@abuzatu we can't support Mac at this moment for support. We will do it later.
You have just 2 options as system on your computer (not VM)
 
1) Ubuntu 22.04 LTS (or Linux Mint based on Ubuntu 22.04 LTS or newer)
2) Windows 10 or 11.

Which option do you prefer?

Regards

**Comment by abuzatu** [comment]
Fair enough, but you make it sound like you offer a new computer too, which I assume is not the case? :)

**Comment by abuzatu** [comment]
@banica this should be assigned to you as you have the task to make the Power BI cloud account to have the pro licence.

**Comment by banica** [comment]
@abuzatu ok, i've unassigned you.

The Pro license is included in Microsoft 365 E5 license. So, if you can't properly use Windows on your computer (not in VM) it will not work.

There is a workaround that i am using, but i am using mostly Ubuntu 22.04 (not as VM).

So you have the 2 options:
1) Ubuntu (not VM).
2) Windows (not VM).

Which one do you prefer?

**Comment by abuzatu** [comment]
You are talking about Power BI to run locally on a computer. But at the hackaton you gave us access to Power BI in the cloud. The cloud Power BI should work independent of my local computer. I can have no computer and still log into office 365 or similar in the cloud. That is the whole idea of the cloud. 

Can you give us access to a cloud Power BI?

**Comment by banica** [comment]
Hi @abuzatu ,

No matter what you do from now on, the Desktop version is Required for real projects.
You have the 2 options, please let me know which one do you prefer. I will guide you step by step based on your decission.

Till then please follow these courses.
https://learn.microsoft.com/en-us/training/browse/?products=power-bi

As a Solution Architect these 2 courses are important for you:
https://learn.microsoft.com/en-us/training/browse/?products=power-bi&roles=solution-architect

Looking forward. 
I will rename this topic to PowerBI. Please open a ticket for each software you need. Regards.

**Comment by abuzatu** [comment]
Thanks for the courses. Are they free?

I will not change the operationg system on my personal computer. It works fine as it is.

If you need me to use Power BI Desktop for this hackaton, you need to provide a computer too. 

In general, I am a data scientist using Python  to solve business problems, not a data analyst to build dashboards.

**Comment by banica** [comment]
@abuzatu you are right...  i can try by Desktop as a Service https://azure.microsoft.com/en-us/solutions/high-performance-computing

Courses are free, of course, or at affordable price (<100$ each).
A data scientist is using Python, of course. But Python rocks on Linux, sometimes on Windows. On Mac it's not performing at all well but this is another story.

**Comment by abuzatu** [comment]
Even on my Mac I actually code in Python on Linux I code inside a Linux Docker Container, which I then deploy in production on a Linux virtual private server (VPS). It works very well. In previous hackaton I was able to both build a simulation and deploy it in one day.
